START TRANSACTION;

DROP TABLE IF EXISTS sensor_readings;
DROP TABLE IF EXISTS dataset;
DROP TABLE IF EXISTS apu_failures;


CREATE TABLE sensor_readings (
    index INTEGER PRIMARY KEY,
    timestamp TEXT NOT NULL,
    TP2 DOUBLE PRECISION NOT NULL,
    TP3 DOUBLE PRECISION NOT NULL,
    H1 DOUBLE PRECISION NOT NULL,
    DV_pressure DOUBLE PRECISION NOT NULL,
    Reservoirs DOUBLE PRECISION NOT NULL,
    Oil_temperature DOUBLE PRECISION NOT NULL,
    Motor_current DOUBLE PRECISION NOT NULL,
    COMP DOUBLE PRECISION NOT NULL,
    DV_eletric DOUBLE PRECISION NOT NULL,
    Towers DOUBLE PRECISION NOT NULL,
    MPG DOUBLE PRECISION NOT NULL,
    LPS DOUBLE PRECISION NOT NULL,
    Pressure_switch DOUBLE PRECISION NOT NULL,
    Oil_level DOUBLE PRECISION NOT NULL,
    Caudal_impulses DOUBLE PRECISION NOT NULL
);

CREATE TABLE apu_failures (
    event_id SERIAL PRIMARY KEY,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    duration_minutes INT,
    severity VARCHAR(10)
);



COMMIT;
