START TRANSACTION

CREATE TABLE dataset (
    index INTEGER PRIMARY KEY,
    timestamp TEXT NOT NULL,
    TP2 DOUBLE PRECISION NOT NULL,
    TP3 DOUBLE PRECISION NOT NULL,
    H1 DOUBLE PRECISION NOT NULL,
    DV_pressure DOUBLE PRECISION NOT NULL,
    Reservoirs DOUBLE PRECISION NOT NULL,
    Oil_temperature DOUBLE PRECISION NOT NULL,
    Motor_current DOUBLE PRECISION NOT NULL,
    COMP DOUBLE PRECISION NOT NULL,
    DV_eletric DOUBLE PRECISION NOT NULL,
    Towers DOUBLE PRECISION NOT NULL,
    MPG DOUBLE PRECISION NOT NULL,
    LPS DOUBLE PRECISION NOT NULL,
    Pressure_switch DOUBLE PRECISION NOT NULL,
    Oil_level DOUBLE PRECISION NOT NULL,
    Caudal_impulses DOUBLE PRECISION NOT NULL
);


COMMIT;
